import '@mantine/core/styles.css';
import './global.css';

import { ColorSchemeScript } from '@mantine/core';
import { ThemeProvider } from '@org/theme';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
